/*
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/

class Solution {
public:
    char findTheDifference(string s, string t) {
    //1. XOR
        s += t; int c = 0;
        for(auto x: s)
        {
            c ^= x;
        }
        return c;
        
    //2. FOR LOOP
        int n = s.size();
        for(int i=0; i<n; i++){
            if(s[i] != t[i]){
                return t[i];
            }
        }
        return t[n];
    }
};
